"""initial_enterprise_schema

Revision ID: 226ea12e772a
Revises: 
Create Date: 2026-07-16 15:45:39.068345

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '226ea12e772a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orders_id_comanda'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_culoare_id_culoare'), table_name='culoare')
    op.drop_table('culoare')
    op.drop_index(op.f('ix_sezon_id_sezon'), table_name='sezon')
    op.drop_table('sezon')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_forma_id_forma'), table_name='forma')
    op.drop_table('forma')
    op.drop_index(op.f('ix_parfum_id_parfum'), table_name='parfum')
    op.drop_table('parfum')
    op.drop_index(op.f('ix_customers_email'), table_name='customers')
    op.drop_index(op.f('ix_customers_id_client'), table_name='customers')
    op.drop_table('customers')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id_client', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nume', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('telefon', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id_client', name=op.f('customers_pkey'))
    )
    op.create_index(op.f('ix_customers_id_client'), 'customers', ['id_client'], unique=False)
    op.create_index(op.f('ix_customers_email'), 'customers', ['email'], unique=True)
    op.create_table('parfum',
    sa.Column('id_parfum', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nume', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id_parfum', name=op.f('parfum_pkey'))
    )
    op.create_index(op.f('ix_parfum_id_parfum'), 'parfum', ['id_parfum'], unique=False)
    op.create_table('forma',
    sa.Column('id_forma', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nume', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id_forma', name=op.f('forma_pkey'))
    )
    op.create_index(op.f('ix_forma_id_forma'), 'forma', ['id_forma'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('full_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('users_pkey'))
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('sezon',
    sa.Column('id_sezon', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nume', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id_sezon', name=op.f('sezon_pkey'))
    )
    op.create_index(op.f('ix_sezon_id_sezon'), 'sezon', ['id_sezon'], unique=False)
    op.create_table('culoare',
    sa.Column('id_culoare', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nume', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id_culoare', name=op.f('culoare_pkey'))
    )
    op.create_index(op.f('ix_culoare_id_culoare'), 'culoare', ['id_culoare'], unique=False)
    op.create_table('orders',
    sa.Column('id_comanda', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_client', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_client'], ['customers.id_client'], name=op.f('orders_id_client_fkey')),
    sa.PrimaryKeyConstraint('id_comanda', name=op.f('orders_pkey'))
    )
    op.create_index(op.f('ix_orders_id_comanda'), 'orders', ['id_comanda'], unique=False)
    # ### end Alembic commands ###
