"""creare_tabele_checkout_si_comenzi

Revision ID: 3d6987eb1f4b
Revises: a6daabb06edd
Create Date: 2026-07-16 18:01:50.210518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d6987eb1f4b'
down_revision: Union[str, Sequence[str], None] = 'a6daabb06edd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
